sudo: false

language: node_js
node_js:
  - 9

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - newman --version

script:
  - newman run "TestingRestApi/3/1. collection.json" -d "TestingRestApi/3/1. data.json"
  - newman run "TestingRestApi/3/2. collection.json" -d "TestingRestApi/3/2. data.json"

branches:
  only:
    - master
    - develop

deploy:
  provider: pages
  skip_cleanup: true
  github_token: b6945a9281ae9c6cd2126fde878e69bce767d932  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

  # provider: heroku
  # app: "obscure-refuge-37874"
  # api_key:
  #   secure: "3f6f0b59-71cf-438b-a417-aa76a20b83b8"